CREATE TABLE USER_INFO
(
  USER_ID    INTEGER AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(45),
  LAST_NAME  VARCHAR(45)
);
CREATE TABLE PHONE_NUMBERS
(
  PHONE_NUMBER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  PHONE_NUMBER    VARCHAR(12),
  CONSTRAINT PHONE_NUMBERS_USER_INFO_USER_ID_FK FOREIGN KEY (PHONE_NUMBER_ID) REFERENCES USER_INFO (USER_ID)
);
CREATE TABLE EMAIL_ADDRESSES
(
  EMAIL_ADDRESS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  EMAIL_ADDRESS    VARCHAR(45),
  CONSTRAINT EMAIL_ADDRESSES_USER_INFO_USER_ID_FK FOREIGN KEY (EMAIL_ADDRESS_ID) REFERENCES USER_INFO (USER_ID)
);
