CREATE TABLE USER_INFO
(
  USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  FIRST_NAME INTEGER,
  LAST_NAME INTEGER
);
CREATE TABLE PHONE_NUMBERS
(
  PHONE_NUMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PHONE_NUMBER VARCHAR(12)
);
CREATE TABLE EMAIL_ADDRESSES
(
  EMAIL_ADDRESS_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL_ADDRESS VARCHAR(45)
);
ALTER TABLE PHONE_NUMBERS ADD FOREIGN KEY (PHONE_NUMBER_ID) REFERENCES USER_INFO (USER_ID);
ALTER TABLE EMAIL_ADDRESSES ADD FOREIGN KEY (EMAIL_ADDRESS_ID) REFERENCES USER_INFO (USER_ID);
