CREATE TABLE USER_INFO
(
  USER_ID    INTEGER AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(45),
  LAST_NAME  VARCHAR(45)
);
CREATE TABLE PHONE_NUMBERS
(
  PHONE_NUMBER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  PHONE_NUMBER    VARCHAR(12)
);
CREATE TABLE EMAIL_ADDRESSES
(
  EMAIL_ADDRESS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  EMAIL_ADDRESS    VARCHAR(45)
);
ALTER TABLE PHONE_NUMBERS
  ADD FOREIGN KEY (PHONE_NUMBER_ID) REFERENCES USER_INFO (USER_ID);
ALTER TABLE EMAIL_ADDRESSES
  ADD FOREIGN KEY (EMAIL_ADDRESS_ID) REFERENCES USER_INFO (USER_ID);
